spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/libro
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
rawg:
  api:
    token: ENC(UP07gRFAPyUd+J1OFrRvKoEl2Vch1cLUkLJa8GGw1/i+MATZBdpifrtE5Pat3yoMOMB+fD+He6+Y0T3q8FfLvqYq06+7wVsuXUzexqpJ0go=)

telegram:
  bot:
    token: ENC(imzzF9mggh3kLSUpKqAe+T4qVdVGNDcS5t6KF7Oxnxt8pD44g6VsGK7D5/emaT/x3Ay9DpM/x+TuTUQE1cFbddKR8H7JOuQOaAwDT1SvvWc=)
    username: GameMateHelper
