spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/libro
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

rawg:
  api:
    key: ENC(UP07gRFAPyUd+J1OFrRvKoEl2Vch1cLUkLJa8GGw1/i+MATZBdpifrtE5Pat3yoMOMB+fD+He6+Y0T3q8FfLvqYq06+7wVsuXUzexqpJ0go=)

telegram:
  bot:
    token: ENC(imzzF9mggh3kLSUpKqAe+T4qVdVGNDcS5t6KF7Oxnxt8pD44g6VsGK7D5/emaT/x3Ay9DpM/x+TuTUQE1cFbddKR8H7JOuQOaAwDT1SvvWc=)
    username: GameMateHelper